Criação da interface LocadoraRepository
iftopalmas/sistemas-viagem pull request #132
Opened 2023-06-03 03:31 UTC by UandersonFerreira

2023-06-05 22:47 UTC, manoelcampos requested changes

2023-06-05 22:47 UTC, manoelcampos commented on sistema-locadora-veiculo/.env.example
> -DATABASE_USERNAME=sa
Vc deve focar em alterar apenas o que foi pedido na tarefa.
O arquivo .env.example não deve ser alterado. 
Deve voltar o arquivo para como estava antes.

2023-06-05 22:47 UTC, manoelcampos commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/repositories/LocadoraRepository.java
> +public interface LocadoraRepository extends JpaRepository<Locadora, Long> {
Seu repositório não segue o padrão que foi pedido na issue #131. Veja o link indicado lá.

2023-06-05 22:51 UTC, manoelcampos commented
@UandersonFerreira fiz alterações no seu branch. Assim, você precisa baixar tais alterações pelo menu git >> Update Project no IntelliJ (ou ctrl+t)

2023-06-05 23:26 UTC, UandersonFerreira commented on sistema-locadora-veiculo/.env.example
> -DATABASE_USERNAME=sa
O arquivo está da mesma forma que copiei, após a atualização da base de dados que foi feita. Peço que me informe qual era o padrão anterior.

2023-06-05 23:28 UTC, UandersonFerreira commented on sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/repositories/LocadoraRepository.java
> +public interface LocadoraRepository extends JpaRepository<Locadora, Long> {
E qual seria o "padrão" ? Pois na issue não está claro.

2023-06-06 13:24 UTC, manoelcampos approved these changes

2023-06-06 13:28 UTC, merged